- syntax/yagpdbcc/main.vim
This PR adds error highlighting for a few specific error cases. Support for other common issues was attempted, but was too complicated (or apparently impossible) to implement.
Error cases caught:
* **Nested sets of double braces.** This is a relatively common mistake I've seen in the YAGPDB support server, particularly among new programmers. They try to do something like `{{ print "Hello and welcome,", {{.Member.Nick}} }}`, not realizing that the second double-brace set is syntactically incorrect.
* **Variable names containing `$`.** While this is not a particularly common mistake, it's definitely an easy one to catch with regex. Plus, even the best of us occasionally forget a space, yielding something like `if$myVar`.
Error cases attempted:
* **Files longer than 10k characters.**
* …
> Add error highlighting

- CONTRIBUTING.md
s/sumitted/submitted (among other changes)
**Terms**
> repo: fix grammar, spelling in contrib guidelines

- syntax/yagpdbcc/main.vim
Fields are annoying, because there's no way to know what kind of object they really are (short of implementing full type checking, which is not feasible in a little extension like this). For example, in `$myVar.myField`, `myField` could be a normal field or a dictionary key.
We feel it's safer not to highlight than to highlight as any particular data type and risk giving false information. Also, we don't want to make the whole screen a mass of random colors -- leaving some text un-highlighted is a good thing.
**Terms**
> Syntax: Don't highlight fields

- ftplugin/yagpdbcc/functions.vim
Adds a command to quickly copy the entire buffer to the system clipboard, via the `"*` register.
Further details discussed in #6. Closes #6.
**Terms**
> Feature: Yank buffer to system clipboard

- ftdetect/yagpdbcc.vim
This PR reformats the filetype detection script to adhere to autocommand best practices (namely, using autocommand groups that are cleared every time they're sourced, to avoid duplicate autocommand definitions), and uses line continuation as opposed to multiple autocommands.
This change could probably have been pushed directly to master, but there's no harm in PRing either.
**Terms**
> ftdetect: use line continuation and autocmd groups

- syntax/yagpdbcc/main.vim
- test/syntax.vader
This pull request implements correct syntax highlighting of single-character constants denoted by single quotes such as the following:
```go
{{ 'h' }}
{{ '\n' }}
```
As showcased, escape sequences are also valid.
Test cases have been implemented, and are passing locally.
Prior to this change, single quotes were not considered -- instead, the following should showcase the issue and motivation for this patch well.
I took the artistic freedom to fix a typo and format the the test file a bit, so that it is more readable.
**Terms**
> Syntax: Highlight Single-Character Constants

- .github/workflows/ci.yml
- .vintrc.yml
- scripts/vint.py
As discussed, project maintainers agreed on setting up a linting tool
for the Vim script programming language. This commit adds said tool with
a configured GitHub workflow as well as a basic configuration file.
It currently is expected behaviour that the workflow fails, as there are some errors thrown by the linter. 
This does not inhibit mergeability of this pull request and is merely a result of the linter's rather strict configuration.
Let me know what you think, whether it is too strict or not -- Documentation can be found at [Vimjas/vint](https://github.com/Vimjas/vint/wiki).
Closes #16
**Terms**
> ci: set up vint

- README.md
- ftplugin/yagpdbcc/functions.vim
- syntax/yagpdbcc/main.vim
This PR makes some minor changes to style in relevant Vimscript files, so that the recently-merged (#17) CI linting step passes cleanly.
Note that vint has a [bug](https://github.com/Vimjas/vint/issues/329) where their `next-line` syntax isn't recognized, so for now, we work around this by disabling the relevant check for one line, then reenabling it.
**Terms**
> Satisfy vint style checking

- README.md
- ftplugin/yagpdbcc/functions.vim
With this commit, a new configuration variable `g:yagpdb_use_primary` is
introduced, which determines whether to write to the `"*` (PRIMARY) or
`"+` CLIPBOARD register.
The difference in these is, that PRIMARY uses the middle mouse button to
insert its content, whereas CLIPBOARD uses Ctrl + V -- thus, we will
from now on default to writing to `"+`, as that is probably what most
users are used to and expect to happen.
Documentation of this variable has been added to the README file.
Closes #21
**Terms**
> functions/clipboard: config var for clip register

- test/clipboard.vader
- test/syntax.vader
Though still not perfect (i.e., no reporting *what*) failed, this is a
better approach than not telling at all what is being tested. Future
PRs/commits will improve on this commit to improve feedback provided to
developers.
**Terms**
> tests: improve feedback of tests

- .github/workflows/generate.yml
- lua/yagpdbcc.lua
- plugin/yagpdb.lua
- scripts/boilerplate.lua
This pull request fixes a bug introduced by the new completion feature, where we attempt to load a module that might not exist.
Now we simply check if it exists and then load our sources.
It also snips the unnecessary license header from the plugin file, as it is rather unnecessary (also that much boilerplate for a single line is rather silly and the license is implied already).
**Terms**
> completion: only load when nvim-cmp is available

- ftdetect/yagpdbcc.vim
This commit modifies `ftdetect/yagpdbcc.vim` to not use augroups.
The linter warning for autocommands without a group has been disabled as
well.
From `:h ftdetect`:
Note that there is no "augroup" command, this has already been done when
sourcing your file. You could also use the pattern "*" and then check
the contents of the file to recognize it.
**Terms**
> ftdetect: don't use augroups in ftdetect

- Makefile
- test/vimrc
This commit modifies `Makefile` to be OS-agnostic as well as checking
for dependencies, such as python3, git, Neovim, and Vim.
This commit also adds the license header to the `test/vimrc` file, as it
was missing prior.
**Terms**
> build/test: refactor makefile

- .github/CODEOWNERS
This commit modifies CODEOWNERS, so that it reflect the new, current
state of the project with the recently added folders and files.
**Terms**
> codeowners: update codeowner configuration

- .github/workflows/generate.yml
workflows: correctly glob file paths
Previously, the file paths were not correctly globbed with
just ' syntax/' as pattern. This commit fixes this by adding the
"glob-star", letting us fully expand on that path.
**Terms**
> ci: fix generate workflow

- .github/workflows/generate.yml
This commit modifies the generate.yml workflow to use the pre-installed
GitHub CLI which comes on all GitHub-hosted runners. It is used to
properly checkout the pull request, which then allows us to actually
push automagic regeneration of completion sources.
**Terms**
> workflows: use GH-CLI to checkout and push to PR

- .github/workflows/ci.yml
- Makefile
- README.md
This commit refactors the `Makefile` one more time, now adding section
documentation comments, as well as a help and install targets.
The install target has been documented in the README.md.
**Terms**
> build: refactor: add make install and help target

- ftdetect/yagpdbcc.vim
- ftplugin/yagpdbcc/functions.vim
This commit optimises the test for the documented global configuration
variables.
From `:h get()`:
get({list}, {idx}, [, {default}])
Get item {idx} from {list}. When item is not available, return
{default}. Return zero when {default} is omitted.
The benefit of this function is first and foremost readability, as it
only requires one clean call instead of chaining two things together.
Secondly, it is more intuitive to read, as well as easier to maintain.
**Terms**
> refactor: optimise checks for global variables

- ftdetect/yagpdbcc.vim
Previously, we used the `setfiletype` command, which will not override an existing filetype. This was an issue because Vim automatically assigns `.tmpl` files the `template` syntax, and this occurs before our plugin has a chance to tell it otherwise.
We now use `setlocal filetype=yagpdbcc`, which has no qualms about overriding things.
Fixes #33.
**Terms**
> ftdetect: forcibly override existing `.tmpl` filetype

- .github/CODEOWNERS
- .github/workflows/ci.yml
- README.md
- autoload/yagpdbcc.vim
- autoload/yagpdbcc/config.vim
- ftdetect/yagpdbcc.vim
- ftplugin/yagpdbcc/folding.vim
- ftplugin/yagpdbcc/functions.vim
- lua/yagpdbcc.lua
- plugin/yagpdbcc.lua
- plugin/yagpdbcc.vim
- syntax/yagpdbcc.vim
This commit touches up the whole codebase to add basic autoloading
capabilities to this plugin. It also replaces the plugin/yagpdbcc.lua
file with plugin/yagpdbcc.vim, for better compatibility reasons.
This allows us to manipulate both Vim and Neovim to our liking.
The override_ft functionality has been moved to the aforementioned new
file, in hopes that it will work better there; see the issue that the
config variable has to be set before loading, as per the README.
For *reasons*, the note will remain there until we can verify independly
that this is indeed an improvement over the current status quo.
Future work entails smaller refactor commits to make the overall
software more maintainable, as well as extensible, whenever appropriate.
We should also consider getting around managing …
> all: refactor codebase for autoload capabilities

- plugin/yagpdbcc.vim
The `has('lua')` call returns 0 for some reason. This commit modifies it
to test for nvim-0.5 *or higher*, so that it actually works.
Closes #50
**Terms**
> plugin: fix loading of cmp items

- .gitignore
- doc/yagpdbcc.txt
This commit adds documentation for the whole plugin.
Future work entails a way to open documentation on structs and functions
of the yagpdb custom command language.
**Terms**
> doc: document plugin

- README.md
- autoload/yagpdbcc/snippets.vim
- doc/yagpdbcc.txt
- ftplugin/yagpdbcc/snippets.vim
- snippets/UltiSnips/yagpdbcc.snippets
- snippets/neosnippet/yagpdbcc.snip
This patchset adds the basic logic for connecting to a snippet backend, as well as some select snippets for two engines I've deemed worthwhile to support (as I've used both of them at some time already).
It also documents the newly added `g:yagpdbcc_snippet_engine` configuration variable.
**Terms**
> ftplugin: snippets

- .editorconfig
- .gitattributes
- .github/markdownlint.rb
- .github/workflows/ci.yml
- .github/workflows/lint.yml
- .mdlrc
- CONTRIBUTING.md
- README.md
- scripts/vint.py
This commit modifies the ci.yml file to use a matrix strategy to test across
multiple versions, both for Neovim and Vim. Secondly, it moves the former
test-nvim step to a separate job, in hopes that the pipeline will complete
faster.
The second part of this commit includes the new lint.yml file, which now
contains the former vim-lint job, as well as two new jobs; Linting via Pyright
for Python, and markdown via Markdownlint.
Future work might entail caching the dependencies on Vim and Neovim, so that we
can speed up the pipeline even further.
**Terms**
> ci: use a matrix strategy, sep jobs, add linters

- lua/yagpdbcc.lua
- syntax/yagpdbcc/functions.vim
This commit adds the `sendMessageRetID` function back, that might have gone
amiss with a past commit.
**Terms**
> syntax: add missing functions

- autoload/yagpdbcc.vim
- autoload/yagpdbcc/config.vim
- autoload/yagpdbcc/snippets.vim
- syntax/yagpdbcc.vim
- test/autoload.vader
- test/autoload_config.vader
- test/syntax.vader
This patchset adds a plethora of tests to the already existing `syntax.vader` test suite, making extensive use of the `Execute` block to have more granular feedback.
Additionally, it adds a new `autoload.vader` test suite, testing a few of our autoloaded functions for correctness and expected return value.
In the process of adding new tests with regards to how YAGPDB itself handles it, I've also applied appropriate patches to the respective file.
**Terms**
> tests: add more test cases

- autoload/yagpdbcc.vim
- autoload/yagpdbcc/config.vim
- autoload/yagpdbcc/snippets.vim
This commit adds small informative comments to each function within the autoload
directory, documenting their functionality, arguments, and return values.
This is just a relatively small change but I was bored and documentation is always good.
**Terms**
> autoload: document autoloaded functions

- .github/CODEOWNERS
- indent/yagpdbcc.vim
- test/indent.vader
- test/vimrc
This commit adds an indentexpr to tell Vim how to properly indent YAGPDB-CC code.
The script is based on fatih/vim-go's gohtmltmpl.vim indentexpr, 
which YAGPDB custom commands essentially are. Proper credit has been given.
**Terms**
> indent: add indentation logic

- lua/yagpdbcc.lua
- syntax/yagpdbcc/functions.vim
YAGPDB version 2.8.0 adds one new function to their custom command system, `timestampToTime`.
This commit adds these/this new function(s) to the syntax definition.
**Terms**
> syntax: add new functions (v2.8.0)

- lua/yagpdbcc.lua
- syntax/yagpdbcc/functions.vim
`cancelScheduledUniqueCC` was missing (perhaps accidentally removed), this commit adds it (back).
**Terms**
> syntax: add missing `cancelScheduledUniqueCC`

- autoload/yagpdbcc.vim
- autoload/yagpdbcc/config.vim
- autoload/yagpdbcc/util.vim
This patchset moves utility functions to their own namespace `yagpdbcc#util`.
Further it adds two new functions `Error` and `Warn`.
Lastly, these changes are reflected onto the callsites of the respective function.
Additionally, it adds a check for the given snippet engine and warns the user about an unsupported engine.
**Terms**
> autoload: move utility functions to their own namespace

- scripts/vint.py
With the current implementation, developers who keep the `.bundle` directory around and run `make lint`, vint will also be invoked on that directory.
This behaviour is undesirable and confusing -- thus, this commit changes the construction of the command to first glob the project tree for any Vim Script files. Given how globbing a path ignores dotfiles, this was quite straightforward.
The only downside is that now the command is *very* long, however that should not be an issue -- in fact, I believe it is better that way, because it becomes immediately obvious which files were linted, even when no violations were found.
**Terms**
> scripts/vint: exclude `.bundle` from linter

- Makefile
- README.md
Conditionally assign important variables, i.e. python3, nvim, vim, git. That way, developers and users alike can use their own specific programs if required.
Furthermore add support for a DESTDIR which can be user-defined as well during invocation of make. This makes dealing with Windows less of a pain.
Smartly clone to DESTDIR, depending on installation target (Vim vs. Neovim). Give users advice on how to proceed if Windows appears to be running as OS.
We now recursively call out to install-vim and install-nvim. This makes the parent install target cleaner and clarifies what is going on.
Closes l-zeuch/yagpdb.vim#48 ("Proposal: Makefile: Deal with Windows")
**Terms**
> build: deal with Windows

- .github/workflows/ci.yml
- .github/workflows/lint.yml
Add nvim-0.8 to version matrix of the test-nvim job.
Latest stable Neovim release is 0.9; without this change, we'd be
skipping over 0.8 during tests, potentially risking compatibility
issues.
**Terms**
> ci: test against new (n)vim releases

- README.md
- ftdetect/yagpdbcc.vim
Drop support for unnecessary file extensions, as they are too long
and/or confusing / redundant.
Closes #79
Breaking Change:
Support for the following file extensions will be dropped:
* yagpdb
* yagpdbcc
* yag-cc
* yagpdb-cc
**Terms**
> ftdetect: drop support for unnecessary file exts

- lua/yagpdbcc.lua
- syntax/yagpdbcc/functions.vim
See https://github.com/botlabs-gg/yagpdb/releases/tag/v2.29.0:
> publishMessage  and publishResponse has been added to custom command templates.
**Terms**
> syntax/funcs: add publishMessage, publishResponse

- syntax/yagpdbcc.vim
Specifically the `yagStr` region exhibits some odd behaviour (even more so in
conjunction with jo3-l/yag-template-lsp) in which a newline-terminated
double-quoted string extends its match region to EOF, when it should be EOL.
Fix this problem by setting the `keepend` attribute on `yagExpr`, which
disallows contained regions to go past their respective `end` pattern. This
fixes the funky behaviour of `yagStr`, whilst having its respective tests still
pass-
As a side-effect, we have to set `yagNestedBrace` to `extend`, such that the
second nested pair `}}` is highlighted as an error as well. For similar reasons,
we must do the same for `yagRawStr`, as it could theoretically contain legally
nested braces …
> syntax: properly configure syntax regions

- README.md
- doc/yagpdbcc.txt
Add some LSP installation instructions to doc/yagpdbcc.txt and the README; that
way, users not intimately familiar with Neovim's way of configuring a language
server by hand (i.e. not using plugins like Mason) have a simple way to further
enrich their experience.
I opted for a plugin-based approach, because I found that easiest to implement
it that way in my own configuration. Either way, it is a sample configuration
and if users have different approaches, they're more than welcome to use those.
**Terms**
> docs: add LSP installation instructions
